### ISSUE TITLE
Combine multiple parameters

### ISSUE THREAD

**Issue by regstuff** [gmarmstrong/python-datamuse#11]
Is it possible to combine the ml & lc parameters. For eg.
words(ml='destroy', lc='relationship', max=5)

Right now this gives the same result as words(ml='destroy', max=5)
It ignores the lc portion.

**Comment by gmarmstrong** [comment]
For this particular example, the Datamuse API returns the same list for both queries:
https://api.datamuse.com/words?ml=destroy&max=5
https://api.datamuse.com/words?ml=destroy&lc=relationship&max=5

So, `python-datamuse` behaves correctly here. Do you know of another example?

**Comment by regstuff** [comment]
Sorry, guess I wasn't clear. The results ARE the same.
I was wondering if they could be different. So for the second list, we would expect words with meanings like "destroy" which follow "relationship"

**Comment by gmarmstrong** [comment]
This library is just a wrapper for the Datamuse API, so its purpose is to provide a Python interface for using that API. I don't have any control over how the Datamuse service responds, and changing those results is outside the scope of this library. You can contact the Datamuse developers [here](https://www.onelook.com/about.shtml#feedback) (according to the "contact us" link on [Datamuse's website](https://www.datamuse.com/)). This way, the [Java library](https://github.com/sjblair/Datamuse4J), [Node.js module](https://github.com/sjblair/Datamuse4J), and any other programs that use the service can receive the same new features.
