### ISSUE TITLE
I can't get the metadata flags to work

### ISSUE THREAD

**Issue by jobs127** [gmarmstrong/python-datamuse#12]
For example, 

  print_out = api.words(rel_rhy="door", max=5, md=r)  # words that rhyme with "orange"
  print(print_out)

products an error that the API doesn't know what md=r means.

Please help.

**Comment by gmarmstrong** [comment]
Does putting quotes around `r` fix this?

**Comment by jobs127** [comment]
It did.  Thank you for the fast response.  One other question.  I am trying to just do frequency searches against a set of words.  I'm not sure how to do that with the API.  I can do frequency searches for words that "rhyme like" a word, but not the word itself. 

How would I go about trying to do what I suggested.  Basically to just return frequency against actual words I choose.  Thank you!

**Comment by gmarmstrong** [comment]
That's a good question, I haven't tried that before. The `qe` ("query echo") parameter looks like it will return the word itself in the response, so I'd try combining that with the word frequency metadata flag `f`. Unfortunately, it looks like you'll still need to give a normal query, and then use the key as the value for `qe`. It's a pretty roundabout solution, I'm not even sure if those instructions made sense, so try to replicate this: https://api.datamuse.com/words?sp=flower&qe=sp&md=f&max=1

EDIT: This should work: `api.words(sp='flower', qe='sp', md='f', max=1)`

**Comment by gmarmstrong** [comment]
Oh, here's something that might be a little faster: https://api.datamuse.com/words?x=flower&qe=x&md=f

It seems like Datamuse will accept arbitrary keywords as parameters, which we can then feed into `qe`. Using `x` here as an example, but something like `my_temp_variable` might be safer in case Datamuse ever adds an `x` parameter for some reason. This strategy should prevent Datamuse from having to do any extra unnecessary work by looking up similar words: `api.words(x='flower', qe='x', md='f', max=1)`
